.TH "AF_IPCA.PandemicApp" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBL\fP"
.br
.RI "This is the business logic DLL\&. This handles all rules and some validations\&. It does not store information\&. "
.ti -1c
.RI "namespace \fBBO\fP"
.br
.RI "Pandemic App Business Object level DLL\&. Here is where everything is defined "
.ti -1c
.RI "namespace \fBConsoleApp\fP"
.br
.RI "This is the mainspace of this application\&. The frondend "
.ti -1c
.RI "namespace \fBDAO\fP"
.br
.RI "This is the lowest level dll\&. This handles all file and lists mediation\&. It stores information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
