.TH "AF_IPCA.PandemicApp.BL.CrossRules" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.BL.CrossRules \- this class stores the rules that are common to the classes at this level  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAF_IPCA\&.PandemicApp\&.BL\&.DiseaseRules\fP, \fBAF_IPCA\&.PandemicApp\&.BL\&.HospitalRules\fP, and \fBAF_IPCA\&.PandemicApp\&.BL\&.SickPersonRules\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossRules\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBCapitalLetter\fP (string s)"
.br
.RI "will capitalize the first letter\&. "
.in -1c
.SH "Detailed Description"
.PP 
this class stores the rules that are common to the classes at this level 


.PP
Definition at line 21 of file CrossRules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AF_IPCA\&.PandemicApp\&.BL\&.CrossRules\&.CrossRules ()"

.PP
Definition at line 33 of file CrossRules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static string AF_IPCA\&.PandemicApp\&.BL\&.CrossRules\&.CapitalLetter (string s)\fC [static]\fP"

.PP
will capitalize the first letter\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP receives a string as parameter
.RE
.PP
\fBReturns\fP
.RS 4
returns the string with the first letter capitalized
.RE
.PP

.PP
Definition at line 54 of file CrossRules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
