.TH "AF_IPCA.PandemicApp.BO.Disease" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.BO.Disease \- This class handls the diseases\&. It is the template of a disease  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisease\fP ()"
.br
.ti -1c
.RI "\fBDisease\fP (string diseaseType, string \fBdiseaseSintoms\fP, int diseaseIncPeriod)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int? \fBIncubationPeriod\fP\fC [get, set]\fP"
.br
.RI "Manages the diseases incubation period for reference\&. "
.ti -1c
.RI "int \fBDiseaseID\fP\fC [get, private set]\fP"
.br
.RI "Defines the disease ID autoincremented "
.ti -1c
.RI "string \fBTypeOfDisease\fP\fC [get, set]\fP"
.br
.RI "This property handles the type of diseases "
.ti -1c
.RI "string \fBDiseaseSintoms\fP\fC [get, set]\fP"
.br
.RI "describes the disease sintoms "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBdiseaseID\fP"
.br
.ti -1c
.RI "string \fBtypeOfDisease\fP"
.br
.ti -1c
.RI "string \fBdiseaseSintoms\fP"
.br
.ti -1c
.RI "int \fBincubationPeriod\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static int \fBglobalDiseaseID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class handls the diseases\&. It is the template of a disease 


.PP
Definition at line 24 of file Disease\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.Disease ()"

.PP
Definition at line 41 of file Disease\&.cs\&.
.SS "AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.Disease (string diseaseType, string diseaseSintoms, int diseaseIncPeriod)"

.PP
Definition at line 47 of file Disease\&.cs\&.
.SH "Field Documentation"
.PP 
.SS "int AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.diseaseID\fC [private]\fP"

.PP
Definition at line 29 of file Disease\&.cs\&.
.SS "string AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.diseaseSintoms\fC [private]\fP"

.PP
Definition at line 31 of file Disease\&.cs\&.
.SS "int AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.globalDiseaseID\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 28 of file Disease\&.cs\&.
.SS "int AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.incubationPeriod\fC [private]\fP"

.PP
Definition at line 32 of file Disease\&.cs\&.
.SS "string AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.typeOfDisease\fC [private]\fP"

.PP
Definition at line 30 of file Disease\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.DiseaseID\fC [get]\fP, \fC [private set]\fP"

.PP
Defines the disease ID autoincremented 
.PP
Definition at line 79 of file Disease\&.cs\&.
.SS "string AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.DiseaseSintoms\fC [get]\fP, \fC [set]\fP"

.PP
describes the disease sintoms 
.PP
Definition at line 111 of file Disease\&.cs\&.
.SS "int? AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.IncubationPeriod\fC [get]\fP, \fC [set]\fP"

.PP
Manages the diseases incubation period for reference\&. 
.PP
Definition at line 63 of file Disease\&.cs\&.
.SS "string AF_IPCA\&.PandemicApp\&.BO\&.Disease\&.TypeOfDisease\fC [get]\fP, \fC [set]\fP"

.PP
This property handles the type of diseases 
.PP
Definition at line 96 of file Disease\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
