.TH "AF_IPCA.PandemicApp.DAO" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.DAO \- This is the lowest level dll\&. This handles all file and lists mediation\&. It stores information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDiseases\fP"
.br
.RI "this class manages diseases\&. "
.ti -1c
.RI "class \fBHospitals\fP"
.br
.RI "this class handles hospitals\&. "
.ti -1c
.RI "class \fBPandemicExceptions\fP"
.br
.RI "this class handles all the exceptions, on this level\&. "
.ti -1c
.RI "class \fBSickPersons\fP"
.br
.RI "this class handles all the sickpersons objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the lowest level dll\&. This handles all file and lists mediation\&. It stores information\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
