.TH "AF_IPCA.PandemicApp.BL" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.BL \- This is the business logic DLL\&. This handles all rules and some validations\&. It does not store information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCrossRules\fP"
.br
.RI "this class stores the rules that are common to the classes at this level "
.ti -1c
.RI "class \fBDiseaseRules\fP"
.br
.RI "This class mediates the logic on the process realated to diseases "
.ti -1c
.RI "class \fBHospitalRules\fP"
.br
.RI "This class handles the logic and rules in the hospitals portfolio "
.ti -1c
.RI "class \fBSickPersonRules\fP"
.br
.RI "This class handles the comunication between frontend and data "
.in -1c
.SH "Detailed Description"
.PP 
This is the business logic DLL\&. This handles all rules and some validations\&. It does not store information\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
