.TH "AF_IPCA.PandemicApp.BO" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.BO \- Pandemic App Business Object level DLL\&. Here is where everything is defined  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBContactPerson\fP"
.br
.RI "this class handles a person's contact\&. "
.ti -1c
.RI "class \fBDisease\fP"
.br
.RI "This class handls the diseases\&. It is the template of a disease "
.ti -1c
.RI "class \fBDiseaseHistory\fP"
.br
.RI "This class is responsible to manage a person's disease\&. As so, it will become a patient\&. "
.ti -1c
.RI "class \fBEmergencyContactPerson\fP"
.br
.RI "This class is the structure of an emergency contact person\&. It inherits from class \fBPerson\fP "
.ti -1c
.RI "class \fBHospital\fP"
.br
.RI "This will struct the information, if a sickperson is admited at a hospital "
.ti -1c
.RI "class \fBPerson\fP"
.br
.RI "This is \fBPerson\fP's class\&. This will define a person\&. "
.ti -1c
.RI "class \fBSickPerson\fP"
.br
.RI "sickperson class\&. This class handles all information related to a person wich is infected\&. "
.in -1c
.SH "Detailed Description"
.PP 
Pandemic App Business Object level DLL\&. Here is where everything is defined 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
