.TH "AF_IPCA.PandemicApp.ConsoleApp" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_IPCA.PandemicApp.ConsoleApp \- This is the mainspace of this application\&. The frondend  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "Main class\&. Here is the main procedure\&. "
.ti -1c
.RI "class \fBTestScripting\fP"
.br
.RI "This is a testing class\&. It contains code to test and call functions in a testing environment "
.in -1c
.SH "Detailed Description"
.PP 
This is the mainspace of this application\&. The frondend 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
