.TH "C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp Directory Reference" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAF_IPCA\&.PandemicApp\&.BL\fP"
.br
.ti -1c
.RI "directory \fBAF_IPCA\&.PandemicApp\&.BO\fP"
.br
.ti -1c
.RI "directory \fBAF_IPCA\&.PandemicApp\&.DAO\fP"
.br
.ti -1c
.RI "directory \fBPandemicApp\fP"
.br
.in -1c
