.TH "C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.BL/DiseaseRules.cs" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.BL/DiseaseRules.cs
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAF_IPCA\&.PandemicApp\&.BL\&.DiseaseRules\fP"
.br
.RI "This class mediates the logic on the process realated to diseases "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAF_IPCA\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\&.BL\fP"
.br
.RI "This is the business logic DLL\&. This handles all rules and some validations\&. It does not store information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
