.TH "C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.BO/Hospital.cs" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.BO/Hospital.cs
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAF_IPCA\&.PandemicApp\&.BO\&.Hospital\fP"
.br
.RI "This will struct the information, if a sickperson is admited at a hospital "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAF_IPCA\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\&.BO\fP"
.br
.RI "Pandemic App Business Object level DLL\&. Here is where everything is defined "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
