.TH "C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.DAO/PandemicExceptions.cs" 3 "Mon Jun 1 2020" "Version 1.0" "Pandemic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Andre/Desktop/LESI/Ano_1/LP_2/Code/Project/PandemicApp/AF_IPCA.PandemicApp.DAO/PandemicExceptions.cs
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAF_IPCA\&.PandemicApp\&.DAO\&.PandemicExceptions\fP"
.br
.RI "this class handles all the exceptions, on this level\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAF_IPCA\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\fP"
.br
.ti -1c
.RI "namespace \fBAF_IPCA\&.PandemicApp\&.DAO\fP"
.br
.RI "This is the lowest level dll\&. This handles all file and lists mediation\&. It stores information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pandemic from the source code\&.
